### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'Extension')

### ISSUE THREAD

**Issue by hammer-ai** [aguingand/tiptap-markdown#78]
**Describe the bug**
When I run, I get:
```
index.js:58896 Uncaught TypeError: Cannot read properties of undefined (reading 'Extension')
    at eval (tiptap-markdown.umd.js:11:1)
    at eval (tiptap-markdown.umd.js:2:1)
    at eval (tiptap-markdown.umd.js:3:2)
    at ../../node_modules/tiptap-markdown/dist/tiptap-markdown.umd.js (index.js:58633:1)
    at __webpack_require__ (index.js:58893:33)
    at fn (index.js:59145:21)
    at eval (index.ts:13:1)
    at ./src/ui/novel/extensions/index.ts (index.js:12131:1)
    at __webpack_require__ (index.js:58893:33)
    at fn (index.js:59145:21)
eval @ tiptap-markdown.umd.js:11
eval @ tiptap-markdown.umd.js:2
eval @ tiptap-markdown.umd.js:3
../../node_modules/tiptap-markdown/dist/tiptap-markdown.umd.js @ index.js:58633
__webpack_require__ @ index.js:58893
fn @ index.js:59145
eval @ index.ts:13
./src/ui/novel/extensions/index.ts @ index.js:12131
__webpack_require__ @ index.js:58893
fn @ index.js:59145
eval @ extensions.ts:1
./src/ui/extensions.ts @ index.js:11999
__webpack_require__ @ index.js:58893
fn @ index.js:59145
eval @ story-editor.tsx:2
./src/ui/story-editor.tsx @ index.js:12284
__webpack_require__ @ index.js:58893
fn @ index.js:59145
eval @ write-story-page.tsx:7
./src/pages/write-story-page.tsx @ index.js:11955
__webpack_require__ @ index.js:58893
fn @ index.js:59145
eval @ app.tsx:23
./src/app.tsx @ index.js:11757
__webpack_require__ @ index.js:58893
fn @ index.js:59145
eval @ renderer.ts:31
./src/renderer.ts @ index.js:11966
__webpack_require__ @ index.js:58893
(anonymous) @ index.js:60076
(anonymous) @ index.js:60078
```

<img width="1643" alt="Screenshot 2024-09-16 at 10 23 09 PM" src="https://github.com/user-attachments/assets/ebcb8aef-28ac-4055-ab40-49f307509969">

which is happening because `core` is `undefined`.

<img width="1653" alt="Screenshot 2024-09-16 at 10 23 36 PM" src="https://github.com/user-attachments/assets/322d921d-e00c-4214-a3e8-e25eed2ef47c">

**To Reproduce**
I get this when running the code from https://novel.sh/docs/introduction in an Electron app.

**Expected behavior**
I would expect there to not be an exception.

**Screenshots**
See above.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Electron

**Additional context**
Thank you!

**Comment by Bistard** [comment]
I had the exact same issue.

**Comment by Vega-KH** [comment]
I wonder if anyone has found a workaround for this. I am also trying to use tiptap-markdown in an electron application with webpack and getting the same error. I have tried a dozen hacks to get webpack to resolve the dependencies in a way that works with no joy. I'm about to give up and move to Lexical, as it seems TipTap 3.0 won't have Markdown support on initial release, and this project looks to be abandoned.
